name: Syntax Check

on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y
        
      - name: Install dependencies
        run: npm install

      - name: Check syntax in main script
        run: node --check app.js  
